---
applications:
  - guillotina_grpc
  - guillotina.contrib.swagger
databases:
  db:
    storage: DUMMY_FILE
    filename: "g.db"
host: localhost
port: 8080
root_user:
  password: root
cors:
  allow_origin:
    - http://localhost:8080
    - "chrome-extension://*"
  allow_methods:
    - GET
    - POST
    - DELETE
    - HEAD
    - PATCH
    - PUT
    - OPTIONS
  allow_headers:
    - "*"
  expose_headers:
    - "*"
  allow_credentials: true
  max_age: 3660
utilities: []
